CREATE TABLE IF NOT EXISTS menu_edits(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS banners(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS pub_posts(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS login_limits(id TEXT PRIMARY KEY,window INTEGER NOT NULL,attempts INTEGER NOT NULL);
