import assert from 'node:assert/strict';
import {scryptSync} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {createSession,verifySession,verifyPassword,requestSession,sessionCookie} from '../lib/auth.mjs';
import {execute} from '../lib/database.mjs';
process.env.SESSION_SECRET='a'.repeat(64);
const salt='b'.repeat(32);process.env.ADMIN_PASSWORD_HASH=`scrypt:${salt}:${scryptSync('correct-password',salt,64).toString('hex')}`;
assert(verifyPassword('correct-password'));assert(!verifyPassword('wrong-password'));
const now=Date.now();const session=createSession(now);
assert(verifySession(session,now));assert(!verifySession(session+'a',now));assert(!verifySession(session,now+28800001));
assert(requestSession(new Request('https://pub.test',{headers:{cookie:'bunker_admin='+session}})));
assert(!requestSession(new Request('https://pub.test',{headers:{'oai-authenticated-user-email':'owner','oai-authenticated-user-id':'1'}})));
process.env.ADMIN_PASSWORD_HASH+='0';assert(!verifySession(session,now));
assert(sessionCookie('abc').includes('HttpOnly'));process.env.NODE_ENV='production';assert(sessionCookie('abc').includes('Secure'));
const database=new DatabaseSync(':memory:');
const actualFetch=globalThis.fetch;process.env.TURSO_DATABASE_URL='libsql://mock.test';process.env.TURSO_AUTH_TOKEN='test-token';
globalThis.fetch=async(url,options)=>{
 assert.equal(url,'https://mock.test/v2/pipeline');assert.equal(options.headers.Authorization,'Bearer test-token');
 const stmt=JSON.parse(options.body).requests[0].stmt;const args=stmt.args.map(x=>x.type==='integer'||x.type==='float'?Number(x.value):x.type==='null'?null:x.value);
 const prepared=database.prepare(stmt.sql);let rows=[],changes=0;
 if(prepared.columns().length)rows=prepared.all(...args);else changes=Number(prepared.run(...args).changes);
 const names=rows.length?Object.keys(rows[0]):[];
 return Response.json({results:[{type:'ok',response:{result:{cols:names.map(name=>({name})),rows:rows.map(row=>names.map(name=>row[name]===null?{type:'null'}:typeof row[name]==='number'?{type:'integer',value:String(row[name])}:{type:'text',value:row[name]})),affected_row_count:changes}}},{type:'ok',response:{type:'close'}}]});
};
await execute('CREATE TABLE menu_edits(id TEXT PRIMARY KEY,payload TEXT)');
const payload=JSON.stringify({name:'Новий бургер',price:250});
await execute('INSERT INTO menu_edits VALUES(?,?)',['burger',payload]);
assert.deepEqual((await execute('SELECT * FROM menu_edits')).rows,[{id:'burger',payload}]);
await execute('CREATE TABLE login_limits(id TEXT PRIMARY KEY,window INTEGER,attempts INTEGER)');
const sql='INSERT INTO login_limits VALUES(?,?,1) ON CONFLICT(id) DO UPDATE SET attempts=CASE WHEN login_limits.window=excluded.window THEN login_limits.attempts+1 ELSE 1 END,window=excluded.window RETURNING attempts';
for(let i=1;i<=6;i++)assert.equal((await execute(sql,['ip',1])).rows[0].attempts,i);
assert.equal((await execute(sql,['ip',2])).rows[0].attempts,1);
globalThis.fetch=async()=>Response.json({results:[{type:'error',error:{message:'failed'}}]});
await assert.rejects(()=>execute('invalid'),/statement failed/);
globalThis.fetch=actualFetch;database.close();console.log('PASS: password, signed sessions, expiry, rotation, forged headers, cookies, SQL persistence, rate counters, DB failure');
